spring:
  application:
    name: mpesa-stk-push-demo
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mpesa_stk_demo}

  datasource:
    url: jdbc:postgresql://localhost:5432/mpesa_db
    username: postgres
    password: developer
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

  logging:
    level:
      org.hibernate.SQL: DEBUG

server:
  port: 8080

mpesa:
  consumerKey: 1sfxM6C0k1DDF65yKElYyCxfwHgiP8sKjhhHDOCxpaVuOjaV
  consumerSecret: iH709EgpEWDvl2Ix0hr9Q4TwWxayGuziEL8SFptGfbiiKIBa0all9bitLy7NvEx4
  shortCode: 174379
  passKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
  callbackUrl: https://capital-obviously-terrier.ngrok-free.app/api/mpesa/callback
  environment: sandbox

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
